services:

  web:
    image: nginx:latest
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  php:
    image: php:8.1-fpm
    volumes:
      - .:/app

volumes:
  app:
